// flow-typed signature: 84ab4ce71ecd412bc2aed42888539b89
// flow-typed version: <<STUB>>/color-stringify_v1.2.1/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'color-stringify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'color-stringify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'color-stringify/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'color-stringify/index' {
  declare module.exports: $Exports<'color-stringify'>;
}
declare module 'color-stringify/index.js' {
  declare module.exports: $Exports<'color-stringify'>;
}
declare module 'color-stringify/test.js' {
  declare module.exports: $Exports<'color-stringify/test'>;
}
