// flow-typed signature: fbf45927778a9c691c08124c8f92d893
// flow-typed version: <<STUB>>/color-rgba_v2.1.1/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'color-rgba'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'color-rgba' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'color-rgba/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'color-rgba/index' {
  declare module.exports: $Exports<'color-rgba'>;
}
declare module 'color-rgba/index.js' {
  declare module.exports: $Exports<'color-rgba'>;
}
declare module 'color-rgba/test.js' {
  declare module.exports: $Exports<'color-rgba/test'>;
}
